# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test
name: Branch protection

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Branch checker
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Path: ConsoleForGit/ConsoleForGit.sln                                               
      Test_Project_Path: ConsoleForGit/ConsoleForGitTest/ConsoleForGitTest.csproj                  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Build the solution
    - name: Build the solution
      run: dotnet build ${{ env.Solution_Path }} -t:Build  -p:Configuration=${{ matrix.configuration }}
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }}

    # Store build solution
    - name: Store release solution
      if: matrix.configuration == 'Release'
    #  run: echo 'this is 2 strange -' ${{ matrix.configuration }}
      uses: actions/upload-artifact@v3
      with:
        name: release
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
